#!/usr/bin/env bash
# assemble-evidence.sh — build the committed BFS-020 evidence files from the runs,
# so every number in the report can be regenerated instead of transcribed.
#
# usage: assemble-evidence.sh [--work DIR] [--out DIR]
#   expects, under --work:
#     evidence-red/BFS-020-red-<arm>.txt        (the same arms on the UNFIXED tree)
#     evidence-green/BFS-020-green-<arm>.txt    (the same arms on the fixed tree)
#     run-instr-trace/run-instr-trace-1/reader.out   (the mechanism trace)
#     battery-before/battery-before/{battery.txt,battery.csv}
#     battery-after/battery-after/{battery.txt,battery.csv}
#     arms/arms.txt                             (BFS-020-arms.sh all)
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../../.." && pwd)"
WORK=/tmp/bfs020
OUT="$REPO/docs/evidence"
while [ $# -gt 0 ]; do
  case "$1" in
    --work) WORK="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    *) echo "unknown arg $1" >&2; exit 2;;
  esac
done

hdr() { printf '### %s\n### generated by docs/evidence/BFS-020-probes/assemble-evidence.sh from %s\n\n' "$1" "$2"; }

emit() { # emit OUTFILE "header" file...
  local out="$1" title="$2"; shift 2
  { hdr "$title" "$*"; for f in "$@"; do
      [ -f "$f" ] || { echo "(missing: $f)"; continue; }
      echo "──── $f"; sed 's/^/  /' "$f"; echo
    done; } > "$OUT/$out"
  echo "wrote $OUT/$out"
}

pair() { # pair NAME  -> BFS-020-NAME.txt  from the red and green arms
  local name="$1"
  emit "BFS-020-$name.txt" "BFS-020 — $name: the UNFIXED tree, then the FIXED tree" \
    "$WORK/evidence-red/BFS-020-red-$name.txt" "$WORK/evidence-green/BFS-020-green-$name.txt"
}

pair repro
pair timing
pair empty
pair content
pair cost
pair poison
pair rmdir
pair rewrite
pair dupwrite

emit "BFS-020-gitlock.txt" "BFS-020 — the real git lock sequence (write, close, RENAME), traced" \
  "$WORK/evidence-green/BFS-020-green-gitlock.txt"
emit "BFS-020-gitblock.txt" "BFS-020 — the committed battery's git block, verbatim, PASS A and PASS B" \
  "$WORK/evidence-green/BFS-020-green-gitblock.txt"
emit "BFS-020-mechanism.txt" "BFS-020 — the mechanism: the mount's own trace against the caller's clock" \
  "$WORK/run-instr-trace/run-instr-trace-1/reader.out"
emit "BFS-020-battery-before.txt" "BFS-020 — the COMMITTED battery, unfixed tree" \
  "$WORK/battery-before/battery-before/battery.txt" "$WORK/battery-before/battery-before/battery.csv"
emit "BFS-020-battery-after.txt" "BFS-020 — the COMMITTED battery, fixed tree" \
  "$WORK/battery-after/battery-after/battery.txt" "$WORK/battery-after/battery-after/battery.csv"
emit "BFS-020-arms.txt" "BFS-020 — the mutation battery (one mutation per cell, sha256-verified restores)" \
  "$WORK/arms/arms.txt"
emit "BFS-020-put.txt" "BFS-020 — the cost REFERENCE: a raw PUT/GET to the served tree with no mount in the path" \
  "$WORK/putcost.txt"
