#!/usr/bin/env bash
# assemble-evidence.sh — fold the BFS-030 arm outputs into the evidence files the
# row asks for. Every block is copied VERBATIM from a run's own output; only the
# section headers are added, so a reader can trace a claim back to the run.
#
# usage: assemble-evidence.sh [--src DIR ...] [--out DIR]
#   default sources: /tmp/bfs030/evidence3 (batteries), evidence4 (cancel),
#                    evidence5 (cost), evidence6 (negative control), and the
#                    two instrumented /tmp/bfs030/run-* directories.
set -uo pipefail
SRC=(/tmp/bfs030/evidence3 /tmp/bfs030/evidence4 /tmp/bfs030/evidence5 /tmp/bfs030/evidence6)
OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --src) SRC=("$2"); shift 2;;
    --src-add) SRC+=("$2"); shift 2;;
    --out) OUT="$2"; shift 2;;
    *) echo "unknown arg $1" >&2; exit 2;;
  esac
done
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -n "$OUT" ] || OUT="$(cd "$HERE/.." && pwd)"

find_src() {  # find_src <filename> -> the first directory that holds it
  local f="$1" d
  for d in "${SRC[@]}"; do [ -f "$d/$f" ] && { printf '%s' "$d/$f"; return 0; }; done
  return 1
}

collect() {  # collect <outfile> <title> <file...>
  local out="$1" title="$2"; shift 2
  {
    echo "================================================================================"
    echo "$title"
    echo "================================================================================"
  } > "$out"
  local f p
  for f in "$@"; do
    if p=$(find_src "$f"); then
      {
        echo
        echo "### $f"
        cat "$p"
      } >> "$out"
    else
      echo
      echo "### $f :: MISSING (arm not present in the given sources)" >> "$out"
    fi
  done
  echo "wrote $out ($(wc -c <"$out") B)"
}

collect "$OUT/BFS-030-red.txt" \
  "BFS-030 RED — the UNFIXED tree: a failed rewrite destroys the original (sha256 on the server's own disk)" \
  BFS-030-red-trunc_open.txt BFS-030-red-ftrunc_fd.txt BFS-030-red-rplus.txt \
  BFS-030-red-append.txt BFS-030-red-trunc_path.txt BFS-030-red3-serverdown.txt \
  BFS-030-red-noread.txt

collect "$OUT/BFS-030-green.txt" \
  "BFS-030 GREEN — the FIXED tree: every failed write shape leaves the original byte-identical" \
  BFS-030-green3-trunc_open.txt BFS-030-green3-ftrunc_fd.txt BFS-030-green3-rplus.txt \
  BFS-030-green3-append.txt BFS-030-green3-trunc_path.txt BFS-030-green4-serverdown.txt \
  BFS-030-green-noread.txt

collect "$OUT/BFS-030-cancel.txt" \
  "BFS-030 x BFS-039 — cancellation: a killed caller, a dead holder, and the errno vocabulary" \
  BFS-030-cancel4-killtrunc-unfixed.txt BFS-030-cancel4-killtrunc-fixed.txt \
  BFS-030-cancel4-holder-fixed.txt BFS-030-cancel4-errno-fixed.txt

collect "$OUT/BFS-030-cost.txt" \
  "BFS-030 cost — the SUCCESSFUL path before/after, three runs each way, plus the guard's own benchmark" \
  BFS-030-cost-before-buffered.txt BFS-030-cost-after-buffered.txt \
  BFS-030-cost2-before-buffered.txt BFS-030-cost2-after-buffered.txt \
  BFS-030-cost3-before-buffered.txt BFS-030-cost3-after-buffered.txt \
  BFS-030-cost-before-fsync.txt BFS-030-cost-after-fsync.txt

collect "$OUT/BFS-030-negative-control.txt" \
  "BFS-030 NEGATIVE CONTROL — the guard removed: the arms go RED and the package tests fail" \
  BFS-030-negctl2-trunc_open.txt BFS-030-negctl2-ftrunc_fd.txt BFS-030-negctl2-trunc_path.txt

# The control is also RE-RUN here, so the evidence carries the patch applying to the
# fixed tree, the failures it causes, and the sha256-verified restore — generated by
# the run rather than transcribed from one.
{
  echo
  echo "================================================================================"
  echo "### negative-control.sh (re-run by this assembler against the current tree)"
  echo "================================================================================"
  bash "$HERE/negative-control.sh" --repo "$(cd "$HERE/../../.." && pwd)" 2>&1
} >> "$OUT/BFS-030-negative-control.txt"
echo "appended the negative-control run to $OUT/BFS-030-negative-control.txt"

echo
echo "The trace/shape/test blocks are appended by the driver (see the evidence document for their sources)."
