// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/bunker/v1/bunker.proto

package bunkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkConfig_Mode int32

const (
	NetworkConfig_MODE_UNSPECIFIED       NetworkConfig_Mode = 0
	NetworkConfig_MODE_CLOUDFLARE_TUNNEL NetworkConfig_Mode = 1 // Cloudflare Tunnel (named or TryCloudflare)
	NetworkConfig_MODE_TAILSCALE         NetworkConfig_Mode = 2 // Tailscale mesh
	NetworkConfig_MODE_DIRECT            NetworkConfig_Mode = 3 // Direct port (behind load balancer)
)

// Enum value maps for NetworkConfig_Mode.
var (
	NetworkConfig_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_CLOUDFLARE_TUNNEL",
		2: "MODE_TAILSCALE",
		3: "MODE_DIRECT",
	}
	NetworkConfig_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":       0,
		"MODE_CLOUDFLARE_TUNNEL": 1,
		"MODE_TAILSCALE":         2,
		"MODE_DIRECT":            3,
	}
)

func (x NetworkConfig_Mode) Enum() *NetworkConfig_Mode {
	p := new(NetworkConfig_Mode)
	*p = x
	return p
}

func (x NetworkConfig_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkConfig_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bunker_v1_bunker_proto_enumTypes[0].Descriptor()
}

func (NetworkConfig_Mode) Type() protoreflect.EnumType {
	return &file_proto_bunker_v1_bunker_proto_enumTypes[0]
}

func (x NetworkConfig_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkConfig_Mode.Descriptor instead.
func (NetworkConfig_Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{1, 0}
}

type ResourceLimits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuQuota            float64                `protobuf:"fixed64,1,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`                                   // CPU quota (cores), e.g. 2.0
	MemoryMaxBytes      uint64                 `protobuf:"varint,2,opt,name=memory_max_bytes,json=memoryMaxBytes,proto3" json:"memory_max_bytes,omitempty"`                // Memory limit in bytes
	DiskMaxBytes        uint64                 `protobuf:"varint,3,opt,name=disk_max_bytes,json=diskMaxBytes,proto3" json:"disk_max_bytes,omitempty"`                      // Disk quota in bytes
	MaxDockerContainers uint32                 `protobuf:"varint,4,opt,name=max_docker_containers,json=maxDockerContainers,proto3" json:"max_docker_containers,omitempty"` // Max concurrent Docker containers
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetCpuQuota() float64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *ResourceLimits) GetMemoryMaxBytes() uint64 {
	if x != nil {
		return x.MemoryMaxBytes
	}
	return 0
}

func (x *ResourceLimits) GetDiskMaxBytes() uint64 {
	if x != nil {
		return x.DiskMaxBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxDockerContainers() uint32 {
	if x != nil {
		return x.MaxDockerContainers
	}
	return 0
}

type NetworkConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           NetworkConfig_Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=bunker.v1.NetworkConfig_Mode" json:"mode,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                                          // Optional: custom domain for Cloudflare
	Trycloudflare  bool                   `protobuf:"varint,3,opt,name=trycloudflare,proto3" json:"trycloudflare,omitempty"`                           // Use anonymous TryCloudflare tunnel
	PortRangeStart uint32                 `protobuf:"varint,4,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"` // Start of per-agent port range
	PortRangeEnd   uint32                 `protobuf:"varint,5,opt,name=port_range_end,json=portRangeEnd,proto3" json:"port_range_end,omitempty"`       // End of per-agent port range
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkConfig) GetMode() NetworkConfig_Mode {
	if x != nil {
		return x.Mode
	}
	return NetworkConfig_MODE_UNSPECIFIED
}

func (x *NetworkConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *NetworkConfig) GetTrycloudflare() bool {
	if x != nil {
		return x.Trycloudflare
	}
	return false
}

func (x *NetworkConfig) GetPortRangeStart() uint32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *NetworkConfig) GetPortRangeEnd() uint32 {
	if x != nil {
		return x.PortRangeEnd
	}
	return 0
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{2}
}

type ServerInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Hostname           string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds      uint64                 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	AgentCount         uint32                 `protobuf:"varint,4,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	MaxAgents          uint32                 `protobuf:"varint,5,opt,name=max_agents,json=maxAgents,proto3" json:"max_agents,omitempty"`
	TotalResources     *ResourceLimits        `protobuf:"bytes,6,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	AvailableResources *ResourceLimits        `protobuf:"bytes,7,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfoResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerInfoResponse) GetAgentCount() uint32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *ServerInfoResponse) GetMaxAgents() uint32 {
	if x != nil {
		return x.MaxAgents
	}
	return 0
}

func (x *ServerInfoResponse) GetTotalResources() *ResourceLimits {
	if x != nil {
		return x.TotalResources
	}
	return nil
}

func (x *ServerInfoResponse) GetAvailableResources() *ResourceLimits {
	if x != nil {
		return x.AvailableResources
	}
	return nil
}

type ServerMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMetricsRequest) Reset() {
	*x = ServerMetricsRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetricsRequest) ProtoMessage() {}

func (x *ServerMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetricsRequest.ProtoReflect.Descriptor instead.
func (*ServerMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{4}
}

type ServerMetricsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent       float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes       uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes      uint64                 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes         uint64                 `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes        uint64                 `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DockerContainersTotal uint32                 `protobuf:"varint,6,opt,name=docker_containers_total,json=dockerContainersTotal,proto3" json:"docker_containers_total,omitempty"`
	Agents                []*AgentSummary        `protobuf:"bytes,7,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServerMetricsResponse) Reset() {
	*x = ServerMetricsResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetricsResponse) ProtoMessage() {}

func (x *ServerMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetricsResponse.ProtoReflect.Descriptor instead.
func (*ServerMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMetricsResponse) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServerMetricsResponse) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ServerMetricsResponse) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *ServerMetricsResponse) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *ServerMetricsResponse) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *ServerMetricsResponse) GetDockerContainersTotal() uint32 {
	if x != nil {
		return x.DockerContainersTotal
	}
	return 0
}

func (x *ServerMetricsResponse) GetAgents() []*AgentSummary {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // pending, starting, running, stopping, stopped, failed
	Limits           *ResourceLimits        `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt        string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SshfsMount       string                 `protobuf:"bytes,6,opt,name=sshfs_mount,json=sshfsMount,proto3" json:"sshfs_mount,omitempty"`                     // sshfs mount command
	DockerHostTunnel string                 `protobuf:"bytes,7,opt,name=docker_host_tunnel,json=dockerHostTunnel,proto3" json:"docker_host_tunnel,omitempty"` // ssh -L tunnel command
	PublicUrl        string                 `protobuf:"bytes,8,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	PortRangeStart   uint32                 `protobuf:"varint,9,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"`
	PortRangeEnd     uint32                 `protobuf:"varint,10,opt,name=port_range_end,json=portRangeEnd,proto3" json:"port_range_end,omitempty"`
	TailnetIp        string                 `protobuf:"bytes,11,opt,name=tailnet_ip,json=tailnetIp,proto3" json:"tailnet_ip,omitempty"`
	DiskUsedBytes    uint64                 `protobuf:"varint,12,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"` // per-agent disk usage in bytes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentSummary) Reset() {
	*x = AgentSummary{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSummary) ProtoMessage() {}

func (x *AgentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSummary.ProtoReflect.Descriptor instead.
func (*AgentSummary) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{6}
}

func (x *AgentSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentSummary) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *AgentSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AgentSummary) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AgentSummary) GetSshfsMount() string {
	if x != nil {
		return x.SshfsMount
	}
	return ""
}

func (x *AgentSummary) GetDockerHostTunnel() string {
	if x != nil {
		return x.DockerHostTunnel
	}
	return ""
}

func (x *AgentSummary) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *AgentSummary) GetPortRangeStart() uint32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *AgentSummary) GetPortRangeEnd() uint32 {
	if x != nil {
		return x.PortRangeEnd
	}
	return 0
}

func (x *AgentSummary) GetTailnetIp() string {
	if x != nil {
		return x.TailnetIp
	}
	return ""
}

func (x *AgentSummary) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

type SpawnAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                  // Optional: auto-generated if empty
	Limits        *ResourceLimits        `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`                                   // Optional: uses server defaults if empty
	Network       *NetworkConfig         `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`                                 // Optional: uses server defaults if empty
	Ttl           string                 `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`                                         // e.g. "6h", "24h", "7d"
	SshPublicKey  []byte                 `protobuf:"bytes,5,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"` // Optional: push existing key
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgentRequest) Reset() {
	*x = SpawnAgentRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentRequest) ProtoMessage() {}

func (x *SpawnAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentRequest.ProtoReflect.Descriptor instead.
func (*SpawnAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{7}
}

func (x *SpawnAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SpawnAgentRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SpawnAgentRequest) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SpawnAgentRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *SpawnAgentRequest) GetSshPublicKey() []byte {
	if x != nil {
		return x.SshPublicKey
	}
	return nil
}

func (x *SpawnAgentRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SpawnAgentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DockerHostSsh    string                 `protobuf:"bytes,2,opt,name=docker_host_ssh,json=dockerHostSsh,proto3" json:"docker_host_ssh,omitempty"`          // DOCKER_HOST=ssh://agent-N@host
	DockerHostTunnel string                 `protobuf:"bytes,3,opt,name=docker_host_tunnel,json=dockerHostTunnel,proto3" json:"docker_host_tunnel,omitempty"` // ssh -L 2376:... command
	SshfsMount       string                 `protobuf:"bytes,4,opt,name=sshfs_mount,json=sshfsMount,proto3" json:"sshfs_mount,omitempty"`                     // sshfs mount command
	PublicUrl        string                 `protobuf:"bytes,5,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`                        // https://agent-N.trycloudflare.com
	PortRangeStart   uint32                 `protobuf:"varint,6,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"`
	PortRangeEnd     uint32                 `protobuf:"varint,7,opt,name=port_range_end,json=portRangeEnd,proto3" json:"port_range_end,omitempty"`
	SshPrivateKey    string                 `protobuf:"bytes,8,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"` // Generated key (if not pushed)
	Limits           *ResourceLimits        `protobuf:"bytes,9,opt,name=limits,proto3" json:"limits,omitempty"`
	ExpiresAt        string                 `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TailnetIp        string                 `protobuf:"bytes,11,opt,name=tailnet_ip,json=tailnetIp,proto3" json:"tailnet_ip,omitempty"`
	ApiKey           string                 `protobuf:"bytes,12,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // Agent-scoped opaque API sub-key (if auth enabled)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpawnAgentResponse) Reset() {
	*x = SpawnAgentResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentResponse) ProtoMessage() {}

func (x *SpawnAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentResponse.ProtoReflect.Descriptor instead.
func (*SpawnAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{8}
}

func (x *SpawnAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SpawnAgentResponse) GetDockerHostSsh() string {
	if x != nil {
		return x.DockerHostSsh
	}
	return ""
}

func (x *SpawnAgentResponse) GetDockerHostTunnel() string {
	if x != nil {
		return x.DockerHostTunnel
	}
	return ""
}

func (x *SpawnAgentResponse) GetSshfsMount() string {
	if x != nil {
		return x.SshfsMount
	}
	return ""
}

func (x *SpawnAgentResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *SpawnAgentResponse) GetPortRangeStart() uint32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *SpawnAgentResponse) GetPortRangeEnd() uint32 {
	if x != nil {
		return x.PortRangeEnd
	}
	return 0
}

func (x *SpawnAgentResponse) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

func (x *SpawnAgentResponse) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SpawnAgentResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SpawnAgentResponse) GetTailnetIp() string {
	if x != nil {
		return x.TailnetIp
	}
	return ""
}

func (x *SpawnAgentResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type DestroyAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force destroy even if running
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAgentRequest) Reset() {
	*x = DestroyAgentRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAgentRequest) ProtoMessage() {}

func (x *DestroyAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAgentRequest.ProtoReflect.Descriptor instead.
func (*DestroyAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DestroyAgentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DestroyAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // destroyed, not_found, error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAgentResponse) Reset() {
	*x = DestroyAgentResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAgentResponse) ProtoMessage() {}

func (x *DestroyAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAgentResponse.ProtoReflect.Descriptor instead.
func (*DestroyAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DestroyAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // Optional: running, stopped, all
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{11}
}

func (x *ListAgentsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListAgentsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentSummary        `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{12}
}

func (x *ListAgentsResponse) GetAgents() []*AgentSummary {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAgentsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{13}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentSummary          `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{14}
}

func (x *GetAgentResponse) GetAgent() *AgentSummary {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetricsRequest) Reset() {
	*x = AgentMetricsRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetricsRequest) ProtoMessage() {}

func (x *AgentMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetricsRequest.ProtoReflect.Descriptor instead.
func (*AgentMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{15}
}

func (x *AgentMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentMetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CpuUsagePercent   float64                `protobuf:"fixed64,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes   uint64                 `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryLimitBytes  uint64                 `protobuf:"varint,5,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	DiskUsedBytes     uint64                 `protobuf:"varint,6,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskLimitBytes    uint64                 `protobuf:"varint,7,opt,name=disk_limit_bytes,json=diskLimitBytes,proto3" json:"disk_limit_bytes,omitempty"`
	DockerContainers  uint32                 `protobuf:"varint,8,opt,name=docker_containers,json=dockerContainers,proto3" json:"docker_containers,omitempty"`
	Uptime            string                 `protobuf:"bytes,9,opt,name=uptime,proto3" json:"uptime,omitempty"`
	HostLevelFallback bool                   `protobuf:"varint,10,opt,name=host_level_fallback,json=hostLevelFallback,proto3" json:"host_level_fallback,omitempty"` // true when metrics are HOST values, not the agent's own cgroup
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentMetricsResponse) Reset() {
	*x = AgentMetricsResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetricsResponse) ProtoMessage() {}

func (x *AgentMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetricsResponse.ProtoReflect.Descriptor instead.
func (*AgentMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{16}
}

func (x *AgentMetricsResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetricsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentMetricsResponse) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *AgentMetricsResponse) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *AgentMetricsResponse) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *AgentMetricsResponse) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *AgentMetricsResponse) GetDiskLimitBytes() uint64 {
	if x != nil {
		return x.DiskLimitBytes
	}
	return 0
}

func (x *AgentMetricsResponse) GetDockerContainers() uint32 {
	if x != nil {
		return x.DockerContainers
	}
	return 0
}

func (x *AgentMetricsResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *AgentMetricsResponse) GetHostLevelFallback() bool {
	if x != nil {
		return x.HostLevelFallback
	}
	return false
}

type HeartbeatAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAgentRequest) Reset() {
	*x = HeartbeatAgentRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAgentRequest) ProtoMessage() {}

func (x *HeartbeatAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAgentRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,3,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAgentResponse) Reset() {
	*x = HeartbeatAgentResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAgentResponse) ProtoMessage() {}

func (x *HeartbeatAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAgentResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatAgentResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *HeartbeatAgentResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type ExecAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Raw            bool                   `protobuf:"varint,5,opt,name=raw,proto3" json:"raw,omitempty"`                                         // Bypass shell interpretation; exec directly
	ScriptContent  string                 `protobuf:"bytes,6,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"` // Optional: upload and execute this script
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecAgentRequest) Reset() {
	*x = ExecAgentRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecAgentRequest) ProtoMessage() {}

func (x *ExecAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecAgentRequest.ProtoReflect.Descriptor instead.
func (*ExecAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{19}
}

func (x *ExecAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecAgentRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecAgentRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecAgentRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecAgentRequest) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

func (x *ExecAgentRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

type ExecAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ExecAgentResponse_Stdout
	//	*ExecAgentResponse_Stderr
	Output        isExecAgentResponse_Output `protobuf_oneof:"output"`
	ExitCode      int32                      `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecAgentResponse) Reset() {
	*x = ExecAgentResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecAgentResponse) ProtoMessage() {}

func (x *ExecAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecAgentResponse.ProtoReflect.Descriptor instead.
func (*ExecAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{20}
}

func (x *ExecAgentResponse) GetOutput() isExecAgentResponse_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecAgentResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecAgentResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecAgentResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecAgentResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecAgentResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type isExecAgentResponse_Output interface {
	isExecAgentResponse_Output()
}

type ExecAgentResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecAgentResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

func (*ExecAgentResponse_Stdout) isExecAgentResponse_Output() {}

func (*ExecAgentResponse_Stderr) isExecAgentResponse_Output() {}

type RunAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Detach         bool                   `protobuf:"varint,5,opt,name=detach,proto3" json:"detach,omitempty"` // Start as persistent background unit
	TimeoutSeconds uint32                 `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Name           string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"` // Optional name suffix for the unit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunAgentRequest) Reset() {
	*x = RunAgentRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentRequest) ProtoMessage() {}

func (x *RunAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentRequest.ProtoReflect.Descriptor instead.
func (*RunAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{21}
}

func (x *RunAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunAgentRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunAgentRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunAgentRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunAgentRequest) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

func (x *RunAgentRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RunAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RunAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                      // "running", "completed", "failed"
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // -1 for detached (still running)
	UnitName      string                 `protobuf:"bytes,4,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`  // systemd unit name for detached runs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentResponse) Reset() {
	*x = RunAgentResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentResponse) ProtoMessage() {}

func (x *RunAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentResponse.ProtoReflect.Descriptor instead.
func (*RunAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{22}
}

func (x *RunAgentResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunAgentResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunAgentResponse) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{23}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DockerHost    string                 `protobuf:"bytes,3,opt,name=docker_host,json=dockerHost,proto3" json:"docker_host,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,4,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{24}
}

func (x *GetInfoResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetInfoResponse) GetDockerHost() string {
	if x != nil {
		return x.DockerHost
	}
	return ""
}

func (x *GetInfoResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *GetInfoResponse) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *GetInfoResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// QueryAuditRequest carries optional filters for the audit trail. All
// filters are ANDed; empty filters match everything. since/until are
// RFC3339 timestamps (RFC3339Nano accepted) compared against the record's
// ts field.
type QueryAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // exact match on agent_id ("" = all)
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                  // substring match on the procedure, e.g. "/bunker.v1.Bunkerd/SpawnAgent" ("" = all)
	Since         string                 `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`                    // RFC3339 lower bound (inclusive)
	Until         string                 `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`                    // RFC3339 upper bound (inclusive)
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                   // max records to return, most recent first (0 = no limit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditRequest) Reset() {
	*x = QueryAuditRequest{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditRequest) ProtoMessage() {}

func (x *QueryAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditRequest) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{25}
}

func (x *QueryAuditRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *QueryAuditRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *QueryAuditRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *QueryAuditRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *QueryAuditRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// AuditRecord is one audit log entry. Field names mirror the JSONL keys
// written by the daemon (internal/audit Record), so a remote query and a
// local export of the same log are byte-identical in content.
type AuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`                                    // RFC3339Nano UTC timestamp
	Caller        string                 `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`                            // token/agent identity
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                            // full connect procedure, e.g. /bunker.v1.Bunkerd/SpawnAgent
	RemoteAddr    string                 `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`  // client address as seen by the server
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`           // target agent of the request ("" when none)
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // wall time from request start to completion
	Outcome       string                 `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"`                          // "ok" or the connect error code, e.g. "not_found"
	Summary       string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`                          // human-readable request summary
	Hash          string                 `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`                                // SHA-256 hex digest of the canonical record line
	PrevHash      string                 `protobuf:"bytes,10,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`       // hash of the previous record in the chain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{26}
}

func (x *AuditRecord) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *AuditRecord) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *AuditRecord) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditRecord) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *AuditRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuditRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AuditRecord) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditRecord) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AuditRecord) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AuditRecord) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

type QueryAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AuditRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditResponse) Reset() {
	*x = QueryAuditResponse{}
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditResponse) ProtoMessage() {}

func (x *QueryAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bunker_v1_bunker_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditResponse.ProtoReflect.Descriptor instead.
func (*QueryAuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_bunker_v1_bunker_proto_rawDescGZIP(), []int{27}
}

func (x *QueryAuditResponse) GetRecords() []*AuditRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_proto_bunker_v1_bunker_proto protoreflect.FileDescriptor

const file_proto_bunker_v1_bunker_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/bunker/v1/bunker.proto\x12\tbunker.v1\"\xb1\x01\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tcpu_quota\x18\x01 \x01(\x01R\bcpuQuota\x12(\n" +
	"\x10memory_max_bytes\x18\x02 \x01(\x04R\x0ememoryMaxBytes\x12$\n" +
	"\x0edisk_max_bytes\x18\x03 \x01(\x04R\fdiskMaxBytes\x122\n" +
	"\x15max_docker_containers\x18\x04 \x01(\rR\x13maxDockerContainers\"\xaf\x02\n" +
	"\rNetworkConfig\x121\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1d.bunker.v1.NetworkConfig.ModeR\x04mode\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12$\n" +
	"\rtrycloudflare\x18\x03 \x01(\bR\rtrycloudflare\x12(\n" +
	"\x10port_range_start\x18\x04 \x01(\rR\x0eportRangeStart\x12$\n" +
	"\x0eport_range_end\x18\x05 \x01(\rR\fportRangeEnd\"]\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MODE_CLOUDFLARE_TUNNEL\x10\x01\x12\x12\n" +
	"\x0eMODE_TAILSCALE\x10\x02\x12\x0f\n" +
	"\vMODE_DIRECT\x10\x03\"\x13\n" +
	"\x11ServerInfoRequest\"\xc1\x02\n" +
	"\x12ServerInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x12\x1f\n" +
	"\vagent_count\x18\x04 \x01(\rR\n" +
	"agentCount\x12\x1d\n" +
	"\n" +
	"max_agents\x18\x05 \x01(\rR\tmaxAgents\x12B\n" +
	"\x0ftotal_resources\x18\x06 \x01(\v2\x19.bunker.v1.ResourceLimitsR\x0etotalResources\x12J\n" +
	"\x13available_resources\x18\a \x01(\v2\x19.bunker.v1.ResourceLimitsR\x12availableResources\"\x16\n" +
	"\x14ServerMetricsRequest\"\xd8\x02\n" +
	"\x15ServerMetricsResponse\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x04R\x0ediskTotalBytes\x126\n" +
	"\x17docker_containers_total\x18\x06 \x01(\rR\x15dockerContainersTotal\x12/\n" +
	"\x06agents\x18\a \x03(\v2\x17.bunker.v1.AgentSummaryR\x06agents\"\xb7\x03\n" +
	"\fAgentSummary\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x121\n" +
	"\x06limits\x18\x03 \x01(\v2\x19.bunker.v1.ResourceLimitsR\x06limits\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vsshfs_mount\x18\x06 \x01(\tR\n" +
	"sshfsMount\x12,\n" +
	"\x12docker_host_tunnel\x18\a \x01(\tR\x10dockerHostTunnel\x12\x1d\n" +
	"\n" +
	"public_url\x18\b \x01(\tR\tpublicUrl\x12(\n" +
	"\x10port_range_start\x18\t \x01(\rR\x0eportRangeStart\x12$\n" +
	"\x0eport_range_end\x18\n" +
	" \x01(\rR\fportRangeEnd\x12\x1d\n" +
	"\n" +
	"tailnet_ip\x18\v \x01(\tR\ttailnetIp\x12&\n" +
	"\x0fdisk_used_bytes\x18\f \x01(\x04R\rdiskUsedBytes\"\xca\x02\n" +
	"\x11SpawnAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x121\n" +
	"\x06limits\x18\x02 \x01(\v2\x19.bunker.v1.ResourceLimitsR\x06limits\x122\n" +
	"\anetwork\x18\x03 \x01(\v2\x18.bunker.v1.NetworkConfigR\anetwork\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\tR\x03ttl\x12$\n" +
	"\x0essh_public_key\x18\x05 \x01(\fR\fsshPublicKey\x12@\n" +
	"\x06labels\x18\x06 \x03(\v2(.bunker.v1.SpawnAgentRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x03\n" +
	"\x12SpawnAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x0fdocker_host_ssh\x18\x02 \x01(\tR\rdockerHostSsh\x12,\n" +
	"\x12docker_host_tunnel\x18\x03 \x01(\tR\x10dockerHostTunnel\x12\x1f\n" +
	"\vsshfs_mount\x18\x04 \x01(\tR\n" +
	"sshfsMount\x12\x1d\n" +
	"\n" +
	"public_url\x18\x05 \x01(\tR\tpublicUrl\x12(\n" +
	"\x10port_range_start\x18\x06 \x01(\rR\x0eportRangeStart\x12$\n" +
	"\x0eport_range_end\x18\a \x01(\rR\fportRangeEnd\x12&\n" +
	"\x0fssh_private_key\x18\b \x01(\tR\rsshPrivateKey\x121\n" +
	"\x06limits\x18\t \x01(\v2\x19.bunker.v1.ResourceLimitsR\x06limits\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"tailnet_ip\x18\v \x01(\tR\ttailnetIp\x12\x17\n" +
	"\aapi_key\x18\f \x01(\tR\x06apiKey\"F\n" +
	"\x13DestroyAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"I\n" +
	"\x14DestroyAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"t\n" +
	"\x11ListAgentsRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8e\x01\n" +
	"\x12ListAgentsResponse\x12/\n" +
	"\x06agents\x18\x01 \x03(\v2\x17.bunker.v1.AgentSummaryR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"A\n" +
	"\x10GetAgentResponse\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.bunker.v1.AgentSummaryR\x05agent\"0\n" +
	"\x13AgentMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x96\x03\n" +
	"\x14AgentMetricsResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x05 \x01(\x04R\x10memoryLimitBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x06 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_limit_bytes\x18\a \x01(\x04R\x0ediskLimitBytes\x12+\n" +
	"\x11docker_containers\x18\b \x01(\rR\x10dockerContainers\x12\x16\n" +
	"\x06uptime\x18\t \x01(\tR\x06uptime\x12.\n" +
	"\x13host_level_fallback\x18\n" +
	" \x01(\bR\x11hostLevelFallback\"2\n" +
	"\x15HeartbeatAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"v\n" +
	"\x16HeartbeatAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\"\n" +
	"\facknowledged\x18\x03 \x01(\bR\facknowledged\"\xbd\x01\n" +
	"\x10ExecAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\bR\x03raw\x12%\n" +
	"\x0escript_content\x18\x06 \x01(\tR\rscriptContent\"n\n" +
	"\x11ExecAgentResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCodeB\b\n" +
	"\x06output\"\x9e\x02\n" +
	"\x0fRunAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x125\n" +
	"\x03env\x18\x04 \x03(\v2#.bunker.v1.RunAgentRequest.EnvEntryR\x03env\x12\x16\n" +
	"\x06detach\x18\x05 \x01(\bR\x06detach\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\rR\x0etimeoutSeconds\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x10RunAgentResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\tunit_name\x18\x04 \x01(\tR\bunitName\"\x10\n" +
	"\x0eGetInfoRequest\"\xd6\x01\n" +
	"\x0fGetInfoResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vdocker_host\x18\x03 \x01(\tR\n" +
	"dockerHost\x12\x1d\n" +
	"\n" +
	"public_url\x18\x04 \x01(\tR\tpublicUrl\x121\n" +
	"\x06limits\x18\x05 \x01(\v2\x19.bunker.v1.ResourceLimitsR\x06limits\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\"\x88\x01\n" +
	"\x11QueryAuditRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x14\n" +
	"\x05since\x18\x03 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x04 \x01(\tR\x05until\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"\x8f\x02\n" +
	"\vAuditRecord\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x16\n" +
	"\x06caller\x18\x02 \x01(\tR\x06caller\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1f\n" +
	"\vremote_addr\x18\x04 \x01(\tR\n" +
	"remoteAddr\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12\x12\n" +
	"\x04hash\x18\t \x01(\tR\x04hash\x12\x1b\n" +
	"\tprev_hash\x18\n" +
	" \x01(\tR\bprevHash\"F\n" +
	"\x12QueryAuditResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.bunker.v1.AuditRecordR\arecords2\xd6\x06\n" +
	"\aBunkerd\x12I\n" +
	"\n" +
	"ServerInfo\x12\x1c.bunker.v1.ServerInfoRequest\x1a\x1d.bunker.v1.ServerInfoResponse\x12R\n" +
	"\rServerMetrics\x12\x1f.bunker.v1.ServerMetricsRequest\x1a .bunker.v1.ServerMetricsResponse\x12I\n" +
	"\n" +
	"SpawnAgent\x12\x1c.bunker.v1.SpawnAgentRequest\x1a\x1d.bunker.v1.SpawnAgentResponse\x12O\n" +
	"\fDestroyAgent\x12\x1e.bunker.v1.DestroyAgentRequest\x1a\x1f.bunker.v1.DestroyAgentResponse\x12I\n" +
	"\n" +
	"ListAgents\x12\x1c.bunker.v1.ListAgentsRequest\x1a\x1d.bunker.v1.ListAgentsResponse\x12C\n" +
	"\bGetAgent\x12\x1a.bunker.v1.GetAgentRequest\x1a\x1b.bunker.v1.GetAgentResponse\x12O\n" +
	"\fAgentMetrics\x12\x1e.bunker.v1.AgentMetricsRequest\x1a\x1f.bunker.v1.AgentMetricsResponse\x12H\n" +
	"\tExecAgent\x12\x1b.bunker.v1.ExecAgentRequest\x1a\x1c.bunker.v1.ExecAgentResponse0\x01\x12C\n" +
	"\bRunAgent\x12\x1a.bunker.v1.RunAgentRequest\x1a\x1b.bunker.v1.RunAgentResponse\x12U\n" +
	"\x0eHeartbeatAgent\x12 .bunker.v1.HeartbeatAgentRequest\x1a!.bunker.v1.HeartbeatAgentResponse\x12I\n" +
	"\n" +
	"QueryAudit\x12\x1c.bunker.v1.QueryAuditRequest\x1a\x1d.bunker.v1.QueryAuditResponse2\xe7\x01\n" +
	"\x05Agent\x12@\n" +
	"\aGetInfo\x12\x19.bunker.v1.GetInfoRequest\x1a\x1a.bunker.v1.GetInfoResponse\x12J\n" +
	"\aMetrics\x12\x1e.bunker.v1.AgentMetricsRequest\x1a\x1f.bunker.v1.AgentMetricsResponse\x12P\n" +
	"\tHeartbeat\x12 .bunker.v1.HeartbeatAgentRequest\x1a!.bunker.v1.HeartbeatAgentResponseB9Z7github.com/deployBunker/bunker/proto/bunker/v1;bunkerv1b\x06proto3"

var (
	file_proto_bunker_v1_bunker_proto_rawDescOnce sync.Once
	file_proto_bunker_v1_bunker_proto_rawDescData []byte
)

func file_proto_bunker_v1_bunker_proto_rawDescGZIP() []byte {
	file_proto_bunker_v1_bunker_proto_rawDescOnce.Do(func() {
		file_proto_bunker_v1_bunker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bunker_v1_bunker_proto_rawDesc), len(file_proto_bunker_v1_bunker_proto_rawDesc)))
	})
	return file_proto_bunker_v1_bunker_proto_rawDescData
}

var file_proto_bunker_v1_bunker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bunker_v1_bunker_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_bunker_v1_bunker_proto_goTypes = []any{
	(NetworkConfig_Mode)(0),        // 0: bunker.v1.NetworkConfig.Mode
	(*ResourceLimits)(nil),         // 1: bunker.v1.ResourceLimits
	(*NetworkConfig)(nil),          // 2: bunker.v1.NetworkConfig
	(*ServerInfoRequest)(nil),      // 3: bunker.v1.ServerInfoRequest
	(*ServerInfoResponse)(nil),     // 4: bunker.v1.ServerInfoResponse
	(*ServerMetricsRequest)(nil),   // 5: bunker.v1.ServerMetricsRequest
	(*ServerMetricsResponse)(nil),  // 6: bunker.v1.ServerMetricsResponse
	(*AgentSummary)(nil),           // 7: bunker.v1.AgentSummary
	(*SpawnAgentRequest)(nil),      // 8: bunker.v1.SpawnAgentRequest
	(*SpawnAgentResponse)(nil),     // 9: bunker.v1.SpawnAgentResponse
	(*DestroyAgentRequest)(nil),    // 10: bunker.v1.DestroyAgentRequest
	(*DestroyAgentResponse)(nil),   // 11: bunker.v1.DestroyAgentResponse
	(*ListAgentsRequest)(nil),      // 12: bunker.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),     // 13: bunker.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),        // 14: bunker.v1.GetAgentRequest
	(*GetAgentResponse)(nil),       // 15: bunker.v1.GetAgentResponse
	(*AgentMetricsRequest)(nil),    // 16: bunker.v1.AgentMetricsRequest
	(*AgentMetricsResponse)(nil),   // 17: bunker.v1.AgentMetricsResponse
	(*HeartbeatAgentRequest)(nil),  // 18: bunker.v1.HeartbeatAgentRequest
	(*HeartbeatAgentResponse)(nil), // 19: bunker.v1.HeartbeatAgentResponse
	(*ExecAgentRequest)(nil),       // 20: bunker.v1.ExecAgentRequest
	(*ExecAgentResponse)(nil),      // 21: bunker.v1.ExecAgentResponse
	(*RunAgentRequest)(nil),        // 22: bunker.v1.RunAgentRequest
	(*RunAgentResponse)(nil),       // 23: bunker.v1.RunAgentResponse
	(*GetInfoRequest)(nil),         // 24: bunker.v1.GetInfoRequest
	(*GetInfoResponse)(nil),        // 25: bunker.v1.GetInfoResponse
	(*QueryAuditRequest)(nil),      // 26: bunker.v1.QueryAuditRequest
	(*AuditRecord)(nil),            // 27: bunker.v1.AuditRecord
	(*QueryAuditResponse)(nil),     // 28: bunker.v1.QueryAuditResponse
	nil,                            // 29: bunker.v1.SpawnAgentRequest.LabelsEntry
	nil,                            // 30: bunker.v1.RunAgentRequest.EnvEntry
}
var file_proto_bunker_v1_bunker_proto_depIdxs = []int32{
	0,  // 0: bunker.v1.NetworkConfig.mode:type_name -> bunker.v1.NetworkConfig.Mode
	1,  // 1: bunker.v1.ServerInfoResponse.total_resources:type_name -> bunker.v1.ResourceLimits
	1,  // 2: bunker.v1.ServerInfoResponse.available_resources:type_name -> bunker.v1.ResourceLimits
	7,  // 3: bunker.v1.ServerMetricsResponse.agents:type_name -> bunker.v1.AgentSummary
	1,  // 4: bunker.v1.AgentSummary.limits:type_name -> bunker.v1.ResourceLimits
	1,  // 5: bunker.v1.SpawnAgentRequest.limits:type_name -> bunker.v1.ResourceLimits
	2,  // 6: bunker.v1.SpawnAgentRequest.network:type_name -> bunker.v1.NetworkConfig
	29, // 7: bunker.v1.SpawnAgentRequest.labels:type_name -> bunker.v1.SpawnAgentRequest.LabelsEntry
	1,  // 8: bunker.v1.SpawnAgentResponse.limits:type_name -> bunker.v1.ResourceLimits
	7,  // 9: bunker.v1.ListAgentsResponse.agents:type_name -> bunker.v1.AgentSummary
	7,  // 10: bunker.v1.GetAgentResponse.agent:type_name -> bunker.v1.AgentSummary
	30, // 11: bunker.v1.RunAgentRequest.env:type_name -> bunker.v1.RunAgentRequest.EnvEntry
	1,  // 12: bunker.v1.GetInfoResponse.limits:type_name -> bunker.v1.ResourceLimits
	27, // 13: bunker.v1.QueryAuditResponse.records:type_name -> bunker.v1.AuditRecord
	3,  // 14: bunker.v1.Bunkerd.ServerInfo:input_type -> bunker.v1.ServerInfoRequest
	5,  // 15: bunker.v1.Bunkerd.ServerMetrics:input_type -> bunker.v1.ServerMetricsRequest
	8,  // 16: bunker.v1.Bunkerd.SpawnAgent:input_type -> bunker.v1.SpawnAgentRequest
	10, // 17: bunker.v1.Bunkerd.DestroyAgent:input_type -> bunker.v1.DestroyAgentRequest
	12, // 18: bunker.v1.Bunkerd.ListAgents:input_type -> bunker.v1.ListAgentsRequest
	14, // 19: bunker.v1.Bunkerd.GetAgent:input_type -> bunker.v1.GetAgentRequest
	16, // 20: bunker.v1.Bunkerd.AgentMetrics:input_type -> bunker.v1.AgentMetricsRequest
	20, // 21: bunker.v1.Bunkerd.ExecAgent:input_type -> bunker.v1.ExecAgentRequest
	22, // 22: bunker.v1.Bunkerd.RunAgent:input_type -> bunker.v1.RunAgentRequest
	18, // 23: bunker.v1.Bunkerd.HeartbeatAgent:input_type -> bunker.v1.HeartbeatAgentRequest
	26, // 24: bunker.v1.Bunkerd.QueryAudit:input_type -> bunker.v1.QueryAuditRequest
	24, // 25: bunker.v1.Agent.GetInfo:input_type -> bunker.v1.GetInfoRequest
	16, // 26: bunker.v1.Agent.Metrics:input_type -> bunker.v1.AgentMetricsRequest
	18, // 27: bunker.v1.Agent.Heartbeat:input_type -> bunker.v1.HeartbeatAgentRequest
	4,  // 28: bunker.v1.Bunkerd.ServerInfo:output_type -> bunker.v1.ServerInfoResponse
	6,  // 29: bunker.v1.Bunkerd.ServerMetrics:output_type -> bunker.v1.ServerMetricsResponse
	9,  // 30: bunker.v1.Bunkerd.SpawnAgent:output_type -> bunker.v1.SpawnAgentResponse
	11, // 31: bunker.v1.Bunkerd.DestroyAgent:output_type -> bunker.v1.DestroyAgentResponse
	13, // 32: bunker.v1.Bunkerd.ListAgents:output_type -> bunker.v1.ListAgentsResponse
	15, // 33: bunker.v1.Bunkerd.GetAgent:output_type -> bunker.v1.GetAgentResponse
	17, // 34: bunker.v1.Bunkerd.AgentMetrics:output_type -> bunker.v1.AgentMetricsResponse
	21, // 35: bunker.v1.Bunkerd.ExecAgent:output_type -> bunker.v1.ExecAgentResponse
	23, // 36: bunker.v1.Bunkerd.RunAgent:output_type -> bunker.v1.RunAgentResponse
	19, // 37: bunker.v1.Bunkerd.HeartbeatAgent:output_type -> bunker.v1.HeartbeatAgentResponse
	28, // 38: bunker.v1.Bunkerd.QueryAudit:output_type -> bunker.v1.QueryAuditResponse
	25, // 39: bunker.v1.Agent.GetInfo:output_type -> bunker.v1.GetInfoResponse
	17, // 40: bunker.v1.Agent.Metrics:output_type -> bunker.v1.AgentMetricsResponse
	19, // 41: bunker.v1.Agent.Heartbeat:output_type -> bunker.v1.HeartbeatAgentResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_bunker_v1_bunker_proto_init() }
func file_proto_bunker_v1_bunker_proto_init() {
	if File_proto_bunker_v1_bunker_proto != nil {
		return
	}
	file_proto_bunker_v1_bunker_proto_msgTypes[20].OneofWrappers = []any{
		(*ExecAgentResponse_Stdout)(nil),
		(*ExecAgentResponse_Stderr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bunker_v1_bunker_proto_rawDesc), len(file_proto_bunker_v1_bunker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_bunker_v1_bunker_proto_goTypes,
		DependencyIndexes: file_proto_bunker_v1_bunker_proto_depIdxs,
		EnumInfos:         file_proto_bunker_v1_bunker_proto_enumTypes,
		MessageInfos:      file_proto_bunker_v1_bunker_proto_msgTypes,
	}.Build()
	File_proto_bunker_v1_bunker_proto = out.File
	file_proto_bunker_v1_bunker_proto_goTypes = nil
	file_proto_bunker_v1_bunker_proto_depIdxs = nil
}
