// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/bunker/v1/bunker.proto

package bunkerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/deployBunker/bunker/proto/bunker/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BunkerdName is the fully-qualified name of the Bunkerd service.
	BunkerdName = "bunker.v1.Bunkerd"
	// AgentName is the fully-qualified name of the Agent service.
	AgentName = "bunker.v1.Agent"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BunkerdServerInfoProcedure is the fully-qualified name of the Bunkerd's ServerInfo RPC.
	BunkerdServerInfoProcedure = "/bunker.v1.Bunkerd/ServerInfo"
	// BunkerdServerMetricsProcedure is the fully-qualified name of the Bunkerd's ServerMetrics RPC.
	BunkerdServerMetricsProcedure = "/bunker.v1.Bunkerd/ServerMetrics"
	// BunkerdSpawnAgentProcedure is the fully-qualified name of the Bunkerd's SpawnAgent RPC.
	BunkerdSpawnAgentProcedure = "/bunker.v1.Bunkerd/SpawnAgent"
	// BunkerdDestroyAgentProcedure is the fully-qualified name of the Bunkerd's DestroyAgent RPC.
	BunkerdDestroyAgentProcedure = "/bunker.v1.Bunkerd/DestroyAgent"
	// BunkerdListAgentsProcedure is the fully-qualified name of the Bunkerd's ListAgents RPC.
	BunkerdListAgentsProcedure = "/bunker.v1.Bunkerd/ListAgents"
	// BunkerdGetAgentProcedure is the fully-qualified name of the Bunkerd's GetAgent RPC.
	BunkerdGetAgentProcedure = "/bunker.v1.Bunkerd/GetAgent"
	// BunkerdAgentMetricsProcedure is the fully-qualified name of the Bunkerd's AgentMetrics RPC.
	BunkerdAgentMetricsProcedure = "/bunker.v1.Bunkerd/AgentMetrics"
	// BunkerdExecAgentProcedure is the fully-qualified name of the Bunkerd's ExecAgent RPC.
	BunkerdExecAgentProcedure = "/bunker.v1.Bunkerd/ExecAgent"
	// BunkerdHeartbeatAgentProcedure is the fully-qualified name of the Bunkerd's HeartbeatAgent RPC.
	BunkerdHeartbeatAgentProcedure = "/bunker.v1.Bunkerd/HeartbeatAgent"
	// AgentGetInfoProcedure is the fully-qualified name of the Agent's GetInfo RPC.
	AgentGetInfoProcedure = "/bunker.v1.Agent/GetInfo"
	// AgentMetricsProcedure is the fully-qualified name of the Agent's Metrics RPC.
	AgentMetricsProcedure = "/bunker.v1.Agent/Metrics"
	// AgentHeartbeatProcedure is the fully-qualified name of the Agent's Heartbeat RPC.
	AgentHeartbeatProcedure = "/bunker.v1.Agent/Heartbeat"
)

// BunkerdClient is a client for the bunker.v1.Bunkerd service.
type BunkerdClient interface {
	// Server management
	ServerInfo(context.Context, *connect.Request[v1.ServerInfoRequest]) (*connect.Response[v1.ServerInfoResponse], error)
	ServerMetrics(context.Context, *connect.Request[v1.ServerMetricsRequest]) (*connect.Response[v1.ServerMetricsResponse], error)
	// Agent lifecycle
	SpawnAgent(context.Context, *connect.Request[v1.SpawnAgentRequest]) (*connect.Response[v1.SpawnAgentResponse], error)
	DestroyAgent(context.Context, *connect.Request[v1.DestroyAgentRequest]) (*connect.Response[v1.DestroyAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	// Agent actions
	AgentMetrics(context.Context, *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error)
	ExecAgent(context.Context, *connect.Request[v1.ExecAgentRequest]) (*connect.ServerStreamForClient[v1.ExecAgentResponse], error)
	HeartbeatAgent(context.Context, *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error)
}

// NewBunkerdClient constructs a client for the bunker.v1.Bunkerd service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBunkerdClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BunkerdClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bunkerdMethods := v1.File_proto_bunker_v1_bunker_proto.Services().ByName("Bunkerd").Methods()
	return &bunkerdClient{
		serverInfo: connect.NewClient[v1.ServerInfoRequest, v1.ServerInfoResponse](
			httpClient,
			baseURL+BunkerdServerInfoProcedure,
			connect.WithSchema(bunkerdMethods.ByName("ServerInfo")),
			connect.WithClientOptions(opts...),
		),
		serverMetrics: connect.NewClient[v1.ServerMetricsRequest, v1.ServerMetricsResponse](
			httpClient,
			baseURL+BunkerdServerMetricsProcedure,
			connect.WithSchema(bunkerdMethods.ByName("ServerMetrics")),
			connect.WithClientOptions(opts...),
		),
		spawnAgent: connect.NewClient[v1.SpawnAgentRequest, v1.SpawnAgentResponse](
			httpClient,
			baseURL+BunkerdSpawnAgentProcedure,
			connect.WithSchema(bunkerdMethods.ByName("SpawnAgent")),
			connect.WithClientOptions(opts...),
		),
		destroyAgent: connect.NewClient[v1.DestroyAgentRequest, v1.DestroyAgentResponse](
			httpClient,
			baseURL+BunkerdDestroyAgentProcedure,
			connect.WithSchema(bunkerdMethods.ByName("DestroyAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+BunkerdListAgentsProcedure,
			connect.WithSchema(bunkerdMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.GetAgentResponse](
			httpClient,
			baseURL+BunkerdGetAgentProcedure,
			connect.WithSchema(bunkerdMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		agentMetrics: connect.NewClient[v1.AgentMetricsRequest, v1.AgentMetricsResponse](
			httpClient,
			baseURL+BunkerdAgentMetricsProcedure,
			connect.WithSchema(bunkerdMethods.ByName("AgentMetrics")),
			connect.WithClientOptions(opts...),
		),
		execAgent: connect.NewClient[v1.ExecAgentRequest, v1.ExecAgentResponse](
			httpClient,
			baseURL+BunkerdExecAgentProcedure,
			connect.WithSchema(bunkerdMethods.ByName("ExecAgent")),
			connect.WithClientOptions(opts...),
		),
		heartbeatAgent: connect.NewClient[v1.HeartbeatAgentRequest, v1.HeartbeatAgentResponse](
			httpClient,
			baseURL+BunkerdHeartbeatAgentProcedure,
			connect.WithSchema(bunkerdMethods.ByName("HeartbeatAgent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bunkerdClient implements BunkerdClient.
type bunkerdClient struct {
	serverInfo     *connect.Client[v1.ServerInfoRequest, v1.ServerInfoResponse]
	serverMetrics  *connect.Client[v1.ServerMetricsRequest, v1.ServerMetricsResponse]
	spawnAgent     *connect.Client[v1.SpawnAgentRequest, v1.SpawnAgentResponse]
	destroyAgent   *connect.Client[v1.DestroyAgentRequest, v1.DestroyAgentResponse]
	listAgents     *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	getAgent       *connect.Client[v1.GetAgentRequest, v1.GetAgentResponse]
	agentMetrics   *connect.Client[v1.AgentMetricsRequest, v1.AgentMetricsResponse]
	execAgent      *connect.Client[v1.ExecAgentRequest, v1.ExecAgentResponse]
	heartbeatAgent *connect.Client[v1.HeartbeatAgentRequest, v1.HeartbeatAgentResponse]
}

// ServerInfo calls bunker.v1.Bunkerd.ServerInfo.
func (c *bunkerdClient) ServerInfo(ctx context.Context, req *connect.Request[v1.ServerInfoRequest]) (*connect.Response[v1.ServerInfoResponse], error) {
	return c.serverInfo.CallUnary(ctx, req)
}

// ServerMetrics calls bunker.v1.Bunkerd.ServerMetrics.
func (c *bunkerdClient) ServerMetrics(ctx context.Context, req *connect.Request[v1.ServerMetricsRequest]) (*connect.Response[v1.ServerMetricsResponse], error) {
	return c.serverMetrics.CallUnary(ctx, req)
}

// SpawnAgent calls bunker.v1.Bunkerd.SpawnAgent.
func (c *bunkerdClient) SpawnAgent(ctx context.Context, req *connect.Request[v1.SpawnAgentRequest]) (*connect.Response[v1.SpawnAgentResponse], error) {
	return c.spawnAgent.CallUnary(ctx, req)
}

// DestroyAgent calls bunker.v1.Bunkerd.DestroyAgent.
func (c *bunkerdClient) DestroyAgent(ctx context.Context, req *connect.Request[v1.DestroyAgentRequest]) (*connect.Response[v1.DestroyAgentResponse], error) {
	return c.destroyAgent.CallUnary(ctx, req)
}

// ListAgents calls bunker.v1.Bunkerd.ListAgents.
func (c *bunkerdClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// GetAgent calls bunker.v1.Bunkerd.GetAgent.
func (c *bunkerdClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// AgentMetrics calls bunker.v1.Bunkerd.AgentMetrics.
func (c *bunkerdClient) AgentMetrics(ctx context.Context, req *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error) {
	return c.agentMetrics.CallUnary(ctx, req)
}

// ExecAgent calls bunker.v1.Bunkerd.ExecAgent.
func (c *bunkerdClient) ExecAgent(ctx context.Context, req *connect.Request[v1.ExecAgentRequest]) (*connect.ServerStreamForClient[v1.ExecAgentResponse], error) {
	return c.execAgent.CallServerStream(ctx, req)
}

// HeartbeatAgent calls bunker.v1.Bunkerd.HeartbeatAgent.
func (c *bunkerdClient) HeartbeatAgent(ctx context.Context, req *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error) {
	return c.heartbeatAgent.CallUnary(ctx, req)
}

// BunkerdHandler is an implementation of the bunker.v1.Bunkerd service.
type BunkerdHandler interface {
	// Server management
	ServerInfo(context.Context, *connect.Request[v1.ServerInfoRequest]) (*connect.Response[v1.ServerInfoResponse], error)
	ServerMetrics(context.Context, *connect.Request[v1.ServerMetricsRequest]) (*connect.Response[v1.ServerMetricsResponse], error)
	// Agent lifecycle
	SpawnAgent(context.Context, *connect.Request[v1.SpawnAgentRequest]) (*connect.Response[v1.SpawnAgentResponse], error)
	DestroyAgent(context.Context, *connect.Request[v1.DestroyAgentRequest]) (*connect.Response[v1.DestroyAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	// Agent actions
	AgentMetrics(context.Context, *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error)
	ExecAgent(context.Context, *connect.Request[v1.ExecAgentRequest], *connect.ServerStream[v1.ExecAgentResponse]) error
	HeartbeatAgent(context.Context, *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error)
}

// NewBunkerdHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBunkerdHandler(svc BunkerdHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bunkerdMethods := v1.File_proto_bunker_v1_bunker_proto.Services().ByName("Bunkerd").Methods()
	bunkerdServerInfoHandler := connect.NewUnaryHandler(
		BunkerdServerInfoProcedure,
		svc.ServerInfo,
		connect.WithSchema(bunkerdMethods.ByName("ServerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdServerMetricsHandler := connect.NewUnaryHandler(
		BunkerdServerMetricsProcedure,
		svc.ServerMetrics,
		connect.WithSchema(bunkerdMethods.ByName("ServerMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdSpawnAgentHandler := connect.NewUnaryHandler(
		BunkerdSpawnAgentProcedure,
		svc.SpawnAgent,
		connect.WithSchema(bunkerdMethods.ByName("SpawnAgent")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdDestroyAgentHandler := connect.NewUnaryHandler(
		BunkerdDestroyAgentProcedure,
		svc.DestroyAgent,
		connect.WithSchema(bunkerdMethods.ByName("DestroyAgent")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdListAgentsHandler := connect.NewUnaryHandler(
		BunkerdListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(bunkerdMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdGetAgentHandler := connect.NewUnaryHandler(
		BunkerdGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(bunkerdMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdAgentMetricsHandler := connect.NewUnaryHandler(
		BunkerdAgentMetricsProcedure,
		svc.AgentMetrics,
		connect.WithSchema(bunkerdMethods.ByName("AgentMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdExecAgentHandler := connect.NewServerStreamHandler(
		BunkerdExecAgentProcedure,
		svc.ExecAgent,
		connect.WithSchema(bunkerdMethods.ByName("ExecAgent")),
		connect.WithHandlerOptions(opts...),
	)
	bunkerdHeartbeatAgentHandler := connect.NewUnaryHandler(
		BunkerdHeartbeatAgentProcedure,
		svc.HeartbeatAgent,
		connect.WithSchema(bunkerdMethods.ByName("HeartbeatAgent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bunker.v1.Bunkerd/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BunkerdServerInfoProcedure:
			bunkerdServerInfoHandler.ServeHTTP(w, r)
		case BunkerdServerMetricsProcedure:
			bunkerdServerMetricsHandler.ServeHTTP(w, r)
		case BunkerdSpawnAgentProcedure:
			bunkerdSpawnAgentHandler.ServeHTTP(w, r)
		case BunkerdDestroyAgentProcedure:
			bunkerdDestroyAgentHandler.ServeHTTP(w, r)
		case BunkerdListAgentsProcedure:
			bunkerdListAgentsHandler.ServeHTTP(w, r)
		case BunkerdGetAgentProcedure:
			bunkerdGetAgentHandler.ServeHTTP(w, r)
		case BunkerdAgentMetricsProcedure:
			bunkerdAgentMetricsHandler.ServeHTTP(w, r)
		case BunkerdExecAgentProcedure:
			bunkerdExecAgentHandler.ServeHTTP(w, r)
		case BunkerdHeartbeatAgentProcedure:
			bunkerdHeartbeatAgentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBunkerdHandler returns CodeUnimplemented from all methods.
type UnimplementedBunkerdHandler struct{}

func (UnimplementedBunkerdHandler) ServerInfo(context.Context, *connect.Request[v1.ServerInfoRequest]) (*connect.Response[v1.ServerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.ServerInfo is not implemented"))
}

func (UnimplementedBunkerdHandler) ServerMetrics(context.Context, *connect.Request[v1.ServerMetricsRequest]) (*connect.Response[v1.ServerMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.ServerMetrics is not implemented"))
}

func (UnimplementedBunkerdHandler) SpawnAgent(context.Context, *connect.Request[v1.SpawnAgentRequest]) (*connect.Response[v1.SpawnAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.SpawnAgent is not implemented"))
}

func (UnimplementedBunkerdHandler) DestroyAgent(context.Context, *connect.Request[v1.DestroyAgentRequest]) (*connect.Response[v1.DestroyAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.DestroyAgent is not implemented"))
}

func (UnimplementedBunkerdHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.ListAgents is not implemented"))
}

func (UnimplementedBunkerdHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.GetAgent is not implemented"))
}

func (UnimplementedBunkerdHandler) AgentMetrics(context.Context, *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.AgentMetrics is not implemented"))
}

func (UnimplementedBunkerdHandler) ExecAgent(context.Context, *connect.Request[v1.ExecAgentRequest], *connect.ServerStream[v1.ExecAgentResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.ExecAgent is not implemented"))
}

func (UnimplementedBunkerdHandler) HeartbeatAgent(context.Context, *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Bunkerd.HeartbeatAgent is not implemented"))
}

// AgentClient is a client for the bunker.v1.Agent service.
type AgentClient interface {
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
	Metrics(context.Context, *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error)
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error)
}

// NewAgentClient constructs a client for the bunker.v1.Agent service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentMethods := v1.File_proto_bunker_v1_bunker_proto.Services().ByName("Agent").Methods()
	return &agentClient{
		getInfo: connect.NewClient[v1.GetInfoRequest, v1.GetInfoResponse](
			httpClient,
			baseURL+AgentGetInfoProcedure,
			connect.WithSchema(agentMethods.ByName("GetInfo")),
			connect.WithClientOptions(opts...),
		),
		metrics: connect.NewClient[v1.AgentMetricsRequest, v1.AgentMetricsResponse](
			httpClient,
			baseURL+AgentMetricsProcedure,
			connect.WithSchema(agentMethods.ByName("Metrics")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatAgentRequest, v1.HeartbeatAgentResponse](
			httpClient,
			baseURL+AgentHeartbeatProcedure,
			connect.WithSchema(agentMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentClient implements AgentClient.
type agentClient struct {
	getInfo   *connect.Client[v1.GetInfoRequest, v1.GetInfoResponse]
	metrics   *connect.Client[v1.AgentMetricsRequest, v1.AgentMetricsResponse]
	heartbeat *connect.Client[v1.HeartbeatAgentRequest, v1.HeartbeatAgentResponse]
}

// GetInfo calls bunker.v1.Agent.GetInfo.
func (c *agentClient) GetInfo(ctx context.Context, req *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return c.getInfo.CallUnary(ctx, req)
}

// Metrics calls bunker.v1.Agent.Metrics.
func (c *agentClient) Metrics(ctx context.Context, req *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error) {
	return c.metrics.CallUnary(ctx, req)
}

// Heartbeat calls bunker.v1.Agent.Heartbeat.
func (c *agentClient) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// AgentHandler is an implementation of the bunker.v1.Agent service.
type AgentHandler interface {
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
	Metrics(context.Context, *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error)
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error)
}

// NewAgentHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentHandler(svc AgentHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentMethods := v1.File_proto_bunker_v1_bunker_proto.Services().ByName("Agent").Methods()
	agentGetInfoHandler := connect.NewUnaryHandler(
		AgentGetInfoProcedure,
		svc.GetInfo,
		connect.WithSchema(agentMethods.ByName("GetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	agentMetricsHandler := connect.NewUnaryHandler(
		AgentMetricsProcedure,
		svc.Metrics,
		connect.WithSchema(agentMethods.ByName("Metrics")),
		connect.WithHandlerOptions(opts...),
	)
	agentHeartbeatHandler := connect.NewUnaryHandler(
		AgentHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(agentMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bunker.v1.Agent/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentGetInfoProcedure:
			agentGetInfoHandler.ServeHTTP(w, r)
		case AgentMetricsProcedure:
			agentMetricsHandler.ServeHTTP(w, r)
		case AgentHeartbeatProcedure:
			agentHeartbeatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentHandler struct{}

func (UnimplementedAgentHandler) GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Agent.GetInfo is not implemented"))
}

func (UnimplementedAgentHandler) Metrics(context.Context, *connect.Request[v1.AgentMetricsRequest]) (*connect.Response[v1.AgentMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Agent.Metrics is not implemented"))
}

func (UnimplementedAgentHandler) Heartbeat(context.Context, *connect.Request[v1.HeartbeatAgentRequest]) (*connect.Response[v1.HeartbeatAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bunker.v1.Agent.Heartbeat is not implemented"))
}
