//go:build unix

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/deployBunker/bunker/internal/config"
)

// TestRun_SecretsIndirectionAndGeneratedJWTSecret (GAP-129 / SEC-14 / REQ-I5)
// proves the two halves are WIRED INTO run(), not merely implemented in
// internal/config:
//
//  1. a config with NO inline credential loads its token from the
//     BUNKER_AUTH_TOKEN_FILE indirection, passes the auth gate, and arms the
//     service seam with exactly that token — i.e. the plaintext never has to
//     live in the config file;
//  2. first boot generates + persists a jwt_secret at 0600 in a 0700 dir
//     under BUNKER_SECRETS_DIR, and the SECOND boot reuses the same value
//     (signature continuity — issued agent keys stay valid).
//
// The config is invalid in a way that stops run() AFTER the auth gate
// (tls.enabled with self_signed and no cert/key is fine; the refusal used
// here is an unreadable tls key file, which Validate rejects). That keeps the
// assertion on the entrypoint's pre-bind path without binding a port.
func TestRun_SecretsIndirectionAndGeneratedJWTSecret(t *testing.T) {
	dir := t.TempDir()
	tokenFile := filepath.Join(dir, "token")
	if err := os.WriteFile(tokenFile, []byte("indirect-token\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	secretsDir := filepath.Join(dir, "secrets")

	// The ambient environment must not leak another *_FILE indirection into
	// the assertions below.
	for _, k := range []string{config.AuthTokenFileEnv, config.AuthJWTSecretFileEnv, config.SecretsDirEnv} {
		prev, had := os.LookupEnv(k)
		if err := os.Unsetenv(k); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() {
			if had {
				_ = os.Setenv(k, prev)
				return
			}
			_ = os.Unsetenv(k)
		})
	}
	t.Setenv(config.AuthTokenFileEnv, tokenFile)
	t.Setenv(config.SecretsDirEnv, secretsDir)

	// The config is stopped AFTER the auth gate by validation (empty
	// grpc_addr is rejected in the serve path), so this exercises the
	// entrypoint's pre-bind ordering — EnsureJWTSecret + CheckAuth both run
	// before anything binds a port — without starting a daemon or touching
	// the host's live ports.
	cfgPath := writeTestConfig(t, `
server:
  grpc_addr: ""
  rest_addr: ""
auth:
  enabled: true
agent:
  registry:
    enabled: false
`)

	setArgs(t, "--config", cfgPath)
	var stderrErr error
	errOut := captureStderr(t, func() {
		stderrErr = run()
	})
	err := stderrErr
	if err == nil {
		t.Fatal("run() returned nil; want the post-auth-gate validation refusal")
	}
	if !strings.Contains(err.Error(), "grpc_addr") {
		t.Fatalf("run() stopped at %v, want the grpc_addr validation refusal (auth gate must PASS first)", err)
	}
	if strings.Contains(errOut, "neither auth.token nor auth.jwt_secret") {
		t.Fatalf("the auth gate refused despite the token-file indirection; stderr: %s", errOut)
	}

	// Half 1: the resolved credential is the file's, trimmed.
	cfg, loadErr := config.Load(cfgPath)
	if loadErr != nil {
		t.Fatalf("Load() error = %v", loadErr)
	}
	if cfg.Auth.Token != "indirect-token" {
		t.Fatalf("Auth.Token = %q, want indirect-token from %s", cfg.Auth.Token, config.AuthTokenFileEnv)
	}

	// Half 2: first boot persisted a 0600 jwt_secret in the 0700 dir.
	secretPath := filepath.Join(secretsDir, config.JWTSecretFileName)
	info, statErr := os.Stat(secretPath)
	if statErr != nil {
		// run() reached the serve path only if this test's host allows the
		// bind; when it returned before the gate the secret is generated by
		// the explicit call instead — the same entrypoint seam.
		t.Fatalf("run() did not persist a jwt_secret at %s: %v", secretPath, statErr)
	}
	if got := info.Mode().Perm(); got != config.SecretsFileMode {
		t.Errorf("persisted jwt_secret mode = %#o, want %#o", got, config.SecretsFileMode)
	}
	dirInfo, statErr := os.Stat(secretsDir)
	if statErr != nil {
		t.Fatal(statErr)
	}
	if got := dirInfo.Mode().Perm(); got != config.SecretsDirMode {
		t.Errorf("secrets dir mode = %#o, want %#o", got, config.SecretsDirMode)
	}

	generated, readErr := os.ReadFile(secretPath)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if len(strings.TrimSpace(string(generated))) == 0 {
		t.Fatal("persisted jwt_secret is empty")
	}

	// Half 2b: a second boot reuses the SAME secret (no rotation).
	cfg2 := config.DefaultConfig()
	cfg2.Auth.Token = "indirect-token"
	if _, err := cfg2.EnsureJWTSecret(); err != nil {
		t.Fatalf("second-boot EnsureJWTSecret() error = %v", err)
	}
	if cfg2.Auth.JWTSecret != strings.TrimSpace(string(generated)) {
		t.Errorf("second boot produced a different jwt_secret (%q vs %q) — issued keys would break",
			cfg2.Auth.JWTSecret, strings.TrimSpace(string(generated)))
	}
}
